Feature/frontend
MissouriMRR/compakt pull request #36
Opened 2024-04-06 18:10 UTC by Malizma333

Fixed bug with how ids were assigned

2024-04-06 18:11 UTC, Malizma333 commented
Documentation needs merge before this

2024-04-09 23:32 UTC, cjhr95 commented
There are some duplicate changes here from #32

2024-04-10 01:21 UTC, cjhr95 requested changes

2024-04-10 01:21 UTC, cjhr95 commented on src/routes/+page.svelte
> +			- The weather API used to gather data is based on the general Rolla area, not specifically our testing location <br>
Change this line to not mention Rolla, we may use it in other cities in the future. Make it more general, like:
```suggestion
			- The weather API used to gather data is based on the general area of the city provided, not specifically the testing location <br>
```

2024-04-11 22:55 UTC, cjhr95 approved these changes
This'll do

2024-04-11 22:58 UTC, merged